version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run serve
    depends_on:
      - mortimap_backend
    networks:
      - mortimap_network
      
  mortimap_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}mortimap_backend
    container_name: mortimap_backend
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
    ports:
      - ${API_PORT:-8000}:8000
    restart: always
    volumes:
      - ./backend:/app
    networks:
      - mortimap_network

networks:
  mortimap_network:
    driver: bridge