version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: "nouchka/sqlite3"
    volumes:
      - ./data:/root/db
  filestorage:
    image: "nginx"
    volumes:
      - ./filestorage:/usr/share/nginx/html:ro
    ports:
      - "8081:80"